defaults:
  - default
  - _self_

histo_dir: SquirrelPlots/${histograms.track_dir_name}/Tracks/Selected/Parameters
ylabel: Tracks
ratio_ylim: [0.75, 2]
with_ratio: false

canvas:
  atlas_label:
    y: 0.8
  other_label:
    y: 0.725
  legend:
    y: 0.55

track_names: "d0, z0, qoverp, z0sin, pt"
num_track_names: 5
track_latex_names: "d_{0}, z_{0}, q/p, z_{0}sin#theta, p_{T}"

histograms:
  - histname: ${gen_str:"reco_{}", ${histograms.track_names}}
    ratio_ylim: ${gen_list:[0.75, 2], ${histograms.num_track_names}}
